version: '3'

services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          #  - http.cors.enabled=true
        - http.port=9200
        - http.cors.enabled=true
        - http.cors.allow-origin=http://localhost:1358,http://192.168.0.134:1358
        - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        - http.cors.allow-credentials=true
      ulimits:
        memlock:
          soft: -1
          hard: -1
      
      volumes:
        - esdata1:/usr/share/elasticsearch/data
      ports:
        - 9200:9200

    web:
      environment:
        - FLASK=app.py
        - FLASK_ENV=development
      build: .
      ports:
        - "5000:5000"
      volumes:
        - .:/app
        - /home/prasad/tumblr:/media
      depends_on:
        - "elasticsearch"
    kibana:

      image: docker.elastic.co/kibana/kibana:6.6.0
      ports:
        - "5601:5601"
      environment:
        # - SERVER_NAME=kibana.tumblr.org
        # - ELASTICSEARCH_HOSTS=["http://elasticsearch"]
        SERVER_NAME: kibana.example.org
        ELASTICSEARCH_HOSTS: '["http://elasticsearch"]'
      depends_on:
        - "elasticsearch"
    # kibano:
    #   image: docker.elastic.co/kibana/kibana:8.2.0
    #   ports:
    #     - "5602:5602"
    #   environment:
    #     # - SERVER_NAME=kibana2.tumblr.org
    #     # - ELASTICSEARCH_HOSTS="http://localhost","http://elasticsearch"
    #     SERVER_NAME: kibana.example.org
    #     ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    #   depends_on:
    #     - "elasticsearch"
  
    # # elasticsearch browser
    dejavu:
      image: appbaseio/dejavu:3.0.0-alpha
      container_name: dejavu
      ports:
       - "1358:1358"
      depends_on:
        - "elasticsearch"

volumes:
    esdata1:
